<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="header">
    <h1 class="page-header">
        Users
    </h1>
    <div class="button-group">
        <?php echo $this->tag->linkTo(array("users/new", "<i class='fa fa-plus'></i> User", 'class'=>'btn btn-success')) ?>
    </div>
</div>

<?php
    echo $this->tag->form(
        array(
            "users/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>
<div class="clearfix">

    <div class="form-group col-sm-4">
        <?php echo $this->tag->textField(array("username", "size" => 30, "class" => "form-control", "id" => "fieldUsername", "placeholder" => "Username")) ?>
    </div>

    <div class="form-group col-sm-4">
        <div class="col-sm-12">
            <?php echo $this->tag->textField(array("email", "size" => 30, "class" => "form-control", "id" => "fieldEmail", "placeholder" => "Email")) ?>
        </div>
    </div>
    <div class="form-group col-sm-4">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-info")) ?>
    </div>
</div>


<?php echo $this->tag->endForm(); ?>


<?php echo $this->getContent() ?>


<div class="row">
    <div class="col-sm-12">
        <?php if(count($page->items) > 0): ?>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Id</th>
                <th>Fullname</th>
                <th>Username</th>
                <th>Banned</th>
                <th>Suspended</th>

                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $user): ?>
                <tr>
                    <td><?php echo $user->id ?></td>
                    <td><?php echo $user->profiles->firstName . ' ' . $user->profiles->lastName ?></td>
                    <td><?php echo $user->username ?></td>
                    <td><i class="fa fa-<?= $user->banned === 1 ? 'check' : 'times' ?>"></i></td>
                    <td><i class="fa fa-<?= $user->suspended === 1 ? 'check' : 'times' ?>"></i></td>

                    <td><?php echo $this->tag->linkTo(array("users/edit/" . $user->id, "Edit", 'class'=>'label label-primary')); ?></td>
                    <td><?php echo $this->tag->linkTo(array("users/delete/" . $user->id, "Delete", 'class'=>'label label-danger')); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php endif; ?>
    </div>
</div>

<div class="row">
    <?php if(count($page->items) > 0): ?>
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("users/index", "First") ?></li>
                <li><?php echo $this->tag->linkTo("users/index?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("users/index?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("users/index?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
    <?php endif; ?>
</div>
